// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cinematic-intro/CurtainPull.tsx": () => import("../components/mockups/cinematic-intro/CurtainPull.tsx"),
  "./components/mockups/cinematic-intro/DrumRoll.tsx": () => import("../components/mockups/cinematic-intro/DrumRoll.tsx"),
  "./components/mockups/stat-boxes/AchievementBadges.tsx": () => import("../components/mockups/stat-boxes/AchievementBadges.tsx"),
  "./components/mockups/stat-boxes/DuoStreak.tsx": () => import("../components/mockups/stat-boxes/DuoStreak.tsx"),
  "./components/mockups/stat-boxes/GlassMetrics.tsx": () => import("../components/mockups/stat-boxes/GlassMetrics.tsx"),
  "./components/mockups/stat-boxes/NeonPulse.tsx": () => import("../components/mockups/stat-boxes/NeonPulse.tsx"),
  "./components/mockups/sort-toggles/Cycle.tsx": () => import("../components/mockups/sort-toggles/Cycle.tsx"),
  "./components/mockups/sort-toggles/IconPopover.tsx": () => import("../components/mockups/sort-toggles/IconPopover.tsx"),
  "./components/mockups/sort-toggles/InlineLabel.tsx": () => import("../components/mockups/sort-toggles/InlineLabel.tsx")
};
