// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cinematic-intro/CurtainPull.tsx": () => import("../components/mockups/cinematic-intro/CurtainPull.tsx"),
  "./components/mockups/cinematic-intro/DrumRoll.tsx": () => import("../components/mockups/cinematic-intro/DrumRoll.tsx")
};
